#!/usr/bin/env bash

JVM_PARAMS="-Xms128m -Xmx512m"
JAR=hyqoztb.jar
DERIVATION_OUTPUT_FILE_PREFIX="dtfs_"
DERIVATION_OUTPUT_DIR="Dtfs"

GENERATION_CF_OUTPUT_FILE_PREFIX="qws_cf_"
GENERATION_DF_OUTPUT_FILE_PREFIX="qws_df_"
GENERATION_OUTPUT_DIR="QWs"

WEIGHTING_BT_OUTPUT_FILE_PREFIX="wqws_bt_"
WEIGHTING_RT_PARTIALCF_OUTPUT_FILE_PREFIX="wqws_rt-partialcf_"
WEIGHTING_RT_FULLCF_OUTPUT_FILE_PREFIX="wqws_rt-fullcf_"
WEIGHTING_RT_DF_OUTPUT_FILE_PREFIX="wqws_rt-df_"
WEIGHTING_OUTPUT_DIR="WQWs"

HQSIGNATURES="1_0_0_0_0_1
1_0_0_1_0_1
2_1_0_0_1_1
2_0_1_0_1_1
2_0_1_1_1_1
3_1_1_1_2_1
3_1_1_1_1_2"
